updating Extracting Resource Group and AKS Cluster Name script 0.1

diff --git a/AKS-Monitoring-pipeline.yml b/AKS-Monitoring-pipeline.yml
--- a/AKS-Monitoring-pipeline.yml
+++ b/AKS-Monitoring-pipeline.yml
@@ -78,14 +78,22 @@ stages:
 
 
           - script: |
-              echo "Extracting Resource Group and AKS Cluster Name..."
-              cd solution
-              export RESOURCE_GROUP=$(terraform output -raw resource_group_name)
-              export AKS_CLUSTER=$(terraform output -raw aks_cluster_name)
-              echo "Resource Group: $RESOURCE_GROUP"
-              echo "AKS Cluster: $AKS_CLUSTER"
-              az aks get-credentials --resource-group "$RESOURCE_GROUP" --name "$AKS_CLUSTER" --overwrite-existing
+             echo "Extracting Resource Group and AKS Cluster Name..."
+             cd solution
+             RESOURCE_GROUP=$(terraform output -raw resource_group_name || echo "NOT_FOUND")
+             AKS_CLUSTER=$(terraform output -raw aks_cluster_name || echo "NOT_FOUND")
+    
+             if [ "$RESOURCE_GROUP" == "NOT_FOUND" ] || [ "$AKS_CLUSTER" == "NOT_FOUND" ]; then
+             echo "Error: Resource group or AKS cluster name not found."
+             exit 1
+             fi
+    
+             echo "Resource Group: $RESOURCE_GROUP"
+             echo "AKS Cluster: $AKS_CLUSTER"
+    
+             az aks get-credentials --resource-group "$RESOURCE_GROUP" --name "$AKS_CLUSTER" --overwrite-existing
             displayName: "Set Kubernetes Context"
+
             
   - stage: Monitoring_Setup
     displayName: "Prometheus and Grafana Setup"
